### ISSUE TITLE
Add AWS Lambda 6.10 support.

### ISSUE THREAD

**Issue by brendo** [CoffeeAndCode/whatdoeslambdasupport.com#11]
https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/

**Comment by jonknapp** [comment]
Nice! Thanks for the heads up, I'll get the site updated this weekend.

**Comment by jonknapp** [comment]
It took longer than expected, but I refactored the deployment and html production code a bit so it will be easier to generate locally and to deploy to AWS (since it uses SAM and not Serverless anymore).

Nothing against Serverless, but AWS is incredibly slow at changing their tech so I know they won't break my deployments. 😄 

It's up at http://www.whatdoeslambdasupport.com and hopefully the DNS will resolve for the naked domain redirect soon.
